MyVideoHost/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csed/',include('csed.urls')),
]

csed/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name='index'),
    path('dbms/', views.dbms, name='detail'),
    path('da/', views.da, name='da'),
    path('ml/', views.ml, name='ml'),
    path('cd/', views.cd, name='cd'),
    path('daa/', views.daa, name='daa'),
]

csed/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Subject(models.Model):
    sub_name = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('publish_date')
    def __str__(self):
        return self.sub_name
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days= 1)
class Video(models.Model):
    subject = models.ForeignKey(Subject,on_delete = models.CASCADE)
    video_link = models.CharField(max_length=200)
    video_date = models.DateTimeField(default = timezone.now())
    def __str__(self):
        return self.video_link
    def was_recorded_recently(self):
        return self.video_date>= timezone.now() - date.timedelta(days = 1)

csed/views.py
from django.http import HttpResponse
from .models import Subject,Video
from django.shortcuts import render
# Create your views here.
def index(request):
    return render(request,'csed/iframe.html')

def dbms(request):
    subject = Subject.objects.get(pk=1)
    return render(request,'csed/main.html',{'subject':subject})
def da(request):
    subject = Subject.objects.get(pk=4)
    return render(request, 'csed/main.html', {'subject': subject})
def ml(request):
    subject = Subject.objects.get(pk=3)
    return render(request,'csed/main.html',{'subject':subject})
def cd(request):
    subject = Subject.objects.get(pk=2)
    return render(request, 'csed/main.html', {'subject': subject})
def daa(request):
    subject = Subject.objects.get(pk=5)
    return render(request,'csed/main.html',{'subject':subject})

csed/templates/csed/iframe.html
<!DOCTYPE html>
<html>
<head>
	<title>
		WebDuniya
	</title>
</head>
<style type="text/css">
	body
	{
		overflow: hidden;
		background: #85d2cd;
	}
	header
	{
		font-size: 20pt;
		text-align: center;
	}
	a
	{
		text-decoration: none;	
	}
	footer
	{
		position: absolute;
		bottom: 5%;
		font:10pt;
		left: 50%;
		right: 50%;

	}
</style>
<body>
<header>
	This website is specially designed  only for CSE-D but anyone can access it
</header>
<br><br>
<p align="center">
	<b>Please Select your Subject </b>
</p>
<table border="2" bgcolor="#efefef" align="center">
	<tr>
		<th width="200px">Subject Name</th>
		<th width="200px">Teacher Name</th>
		<th width="200px">Click Button</th>
	</tr>
	<tr>
		<th>DataBase Management System</th>
		<th>Mr. Vineet Kumar</th>
		<th width="200px"><a href="/csed/dbms/" target="_blank" id="topress">Click Here</a></th>
	</tr>
	<tr>
		<th>Design and Analysis of ALgorithms</th>
		<th>Mr. Twinkle Tyagi</th>
		<th width="200px"><a href="/csed/daa/" target="_blank" id="topress">Click Here</a></th>
	</tr>
	<tr>
		<th>Machine Learning</th>
		<th>Mr. KedarNath</th>
		<th width="200px"><a href="/csed/ml/" target="_blank" id="topress">Click Here</a></th>
	</tr>
	<tr>
		<th>Compiler Design</th>
		<th>Mrs. Ratna Patil</th>
		<th width="200px"><a href="/csed/cd/" target="_blank" id="topress">Click Here</a></th>
	</tr>

	<tr>
		<th>Data Analysis</th>
		<th>Mrs. Surabhi Purwar</th>
		<th width="200px"><a href="/csed/da/" target="_blank" id="topress">Click Here</a></th>
	</tr>
</table>
<br>
<br>
<br>
<p align="Center"><b>Time Table</b></p>
<br>
<br>
<table border="2" bgcolor="#efefef" align="center">
 <tr bgcolor="#fff">
 <th width="150">Time/Days</th>
 <th width="150">Monday</th>
 <th width="150">Tuesday</th>
 <th width="150">Wednesday</th>
 <th width="150" >Thursday</th>
 <th width="150" >Friday</th>
 </tr>
 <tr bgcolor="#fff">
 <th>10:55 AM</th>
 <td width="150">DBMS</td>
 <td width="150">Compiler Design</td>
 <td width="150">DBMS</td>
 <td width="150">Compiler Design</td>
 <td width="150">DBMS</td>
 </tr>
 <tr bgcolor="#fff">
 <th>11:50 AM</th>
 <td width="150">Machine Learning</td>
 <td width="150">Data Analysis</td>
 <td width="150">Machine Learning</td>
 <td width="150">Data Analysis</td>
 <td width="150">Machine Learning</td>
 </tr>
 <tr bgcolor="#fff">
 <th>12:45 PM</th>
 <td width="150">Compiler Design</td>
 <td width="150">DBMS</td>
 <td width="150">Compiler Design</td>
 <td width="150">DBMS</td>
 <td width="150">Compiler Design</td>
 </tr>
 <tr bgcolor="#fff">
 <th>02:35 PM</th>
 <td width="150">Design And Analysis of algorithms</td>
 <td width="150">Design And Analysis of algorithms</td>
 <td width="150">Design And Analysis of algorithms</td>
 <td width="150">Design And Analysis of algorithms</td>
 <td width="150">Design And Analysis of algorithms</td>
 </tr>
 <tr bgcolor="#fff">
 <th>03:30 PM</th>
 
 <td width="150">Data Analysis</td>
 <td width="150">Machine Learning</td>
 
 <td width="150">Data Analysis</td>
 <td width="150">Machine Learning</td>
 <td width="150">Data Analysis</td>
 </tr>
 </table>
</body>
</html>

csed/templates/csed/main.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{{ subject.sub_name }} Video Lectures
	</title>
</head>
<script type="text/javascript">
	function clicked()
	{
		var f = document.getElementById('myid').value;
		document.getElementById('sec2').src = f;	
	}
</script>
<style type="text/css">
	body
	{
		background: #201f1f;
	}
	#vlove
	{
		position: absolute;
		height: 90%;
		width: 90%;
		left: 5%;
		right: 5%;
		top: 5%;
		bottom:5%;
		box-shadow: 5px 10px 18px #888888;
	}
	#sec1
	{
		position: absolute;
		height: 100%;
		width:300px;
		left: 0%;
		top: 0%;
		bottom: 0%;
		overflow: visible;
		background-color:#d2d0c5; 
		opacity: 50%;

	}
	li
	{
		position:relative;
		height: 20px;
		width:100%;
		background-color: black;
		font: white;
		list-style: none;
	}
	#sec2
	{
		position: absolute;
		height: 100%;
		left: 0%;
		width: 100%;
		top: 0%;
		right: 0%;
		bottom: 0%;
		overflow: visible;
		background-color:#d2d0c5; 
		background-color: black;	
	}
	a
	{
		color:white;
		text-decoration: none;
		
	}
	select 
	{
		position: relative;
	}

</style>
<body>
<section id = "vlove">
	
	<iframe id="sec2" src="" name="iframe_a" allowfullscreen></iframe>	
<select id="myid" onclick="clicked();">
	{% for choice in subject.video_set.all %}
	<option value="https://web.microsoftstream.com/embed/video/{{ choice.video_link }}?autoplay=false&amp;showinfo=false" selected>
			{{ subject.sub_name }} {{ choice.video_date }}
	</option>
	{% endfor %}
</select>

</section>
</body>
</html>